### ISSUE TITLE
Error without package.json posthtml property

### ISSUE THREAD

**Issue by sebdeckers** [post-org/post-config#62]
I'm seeing this error when running `posthtml` CLI with a custom config file and without the package.json `posthtml` section.

### Error

```
TypeError: Cannot read property 'plugins' of undefined
    at /Users/seb/Code/sebdeckers/ui-templates/node_modules/post-load-plugins/lib/index.js:1:1358
    at PostHTML.<anonymous> (/Users/seb/Code/sebdeckers/ui-templates/node_modules/posthtml/lib/index.js:143:7)
    at /Users/seb/Code/sebdeckers/ui-templates/node_modules/posthtml/lib/index.js:173:5
    at PostHTML.process (/Users/seb/Code/sebdeckers/ui-templates/node_modules/posthtml/lib/index.js:172:10)
    at processing (/Users/seb/Code/sebdeckers/ui-templates/node_modules/posthtml-cli/cli.js:58:6)
    at /Users/seb/Code/sebdeckers/ui-templates/node_modules/posthtml-cli/cli.js:95:5
    at Array.forEach (native)
    at /Users/seb/Code/sebdeckers/ui-templates/node_modules/posthtml-cli/cli.js:93:9
```

### Command

```
ui-templates 👉 ./node_modules/.bin/posthtml --config posthtml.json
```

### `package.json`

```json
{
  "dependencies": {
    "cssnano": "^3.10.0",
    "htmlnano": "^0.1.5",
    "http-server": "^0.9.0",
    "postcss": "^5.2.11",
    "postcss-cli": "^2.6.0",
    "postcss-cssnext": "^2.9.0",
    "posthtml-cli": "^0.2.12",
    "rimraf": "^2.5.4",
    "stylelint-config-standard": "^15.0.1"
  },
  "devDependencies": {
    "colorguard": "^1.2.0",
    "stylelint": "^7.7.1"
  }
}
```

### `posthtml.json`

```json
{
  "input": "html/**/*.html",
  "output": "public"
}
```

**Comment by sebdeckers** [comment]
Adding `"posthtml": {}` to `package.json` fixes the error but it should not be necessary if I'm already specifying a `--config|-c` argument. Right?

**Comment by GitScrum** [comment]
Hi, thank you for feedback this is very important for me. 

I will try to understand and eliminate the cause as soon as possible.
